version: "3"

services:
  dynamodblocal:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    ports:
      - "${APP_DOCKER_DYNAMODB_LOCAL_PORT-8000}:8000"
    volumes:
      - ./data:/data
    networks:
      - lambda-local
    command: ["-jar", "DynamoDBLocal.jar", "-dbPath", "/data", "-port", "8000", "-sharedDb"]

  dynamodbdmin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "${APP_DOCKER_DYNAMODB_ADMIN_PORT-8001}:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      - dynamodblocal
    networks:
      - lambda-local


networks:
  lambda-local:
    external: true
