AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: study-aws-sam-ts

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  Env:
    Type: String
    AllowedValues:
      - development
      - staging
      - production
    Default: development
  LocalDynamoDbHost:
    Type: String

Resources:
  AppFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dist/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          NODE_ENV: !Ref Env
          LOCAL_DYNAMO_DB_HOST: !Ref LocalDynamoDbHost
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get

    # TaskDynamoDBTable:
    #     Type: AWS::DynamoDB::Table
    #     Properties:
    #         BillingMode: PAY_PER_REQUEST
    #         AttributeDefinitions:
    #             - AttributeName: Id
    #               AttributeType: N
    #         TableName: Task
    #         KeySchema:
    #             - AttributeName: Id
    #               KeyType: HASH

Outputs:
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  AppFunc:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AppFunc.Arn

  AppFuncIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AppFunc.Arn
